stages:
  - quality
  - frontend-testing
  - integration-testing
  - load-testing
  - publish

before_script:
  - mkdir -p /go/src/gitlab.com/prixfixe/
  - cp -rf /builds/prixfixe/prixfixe /go/src/gitlab.com/prixfixe/
  - cd /go/src/gitlab.com/prixfixe/prixfixe

coverage:
  stage: quality
  image: golang:1.17-stretch
  variables:
    GOPATH: "/go"
  script:
    - apt-get update -y && apt-get install -y make git gcc musl-dev
    - make vendor coverage

dependency-injection-check:
  stage: quality
  image: golang:1.17-stretch
  variables:
    GOPATH: "/go"
  script:
    - apt-get update -y && apt-get install -y make git gcc musl-dev
    - go install github.com/google/wire/cmd/wire@latest
    - make rewire

golang-format-check:
  stage: quality
  image: golang:1.17-stretch
  variables:
    GOPATH: "/go"
  script:
    - apt-get update -y && apt-get install -y make git gcc musl-dev
    - if [ $(gofmt -l . | grep -Ev '^vendor\/' | head -c1 | wc -c) -ne 0 ]; then exit 1; fi

golang-lint:
  stage: quality
  image: golangci/golangci-lint:v1.42
  script:
    - go mod vendor
    - golangci-lint run --config=.golangci.yml --deadline=15m
