apiVersion: 1

# Thanks to https://ops.tips/blog/initialize-grafana-with-preconfigured-dashboards/#configuring-grafana
datasources:
  - access: 'proxy' # make grafana perform the requests
    version: 1 # well, versioning
    is_default: true # whether this should be the default DS
    name: 'prometheus' # name of the datasource
    type: 'prometheus' # type of the data source
    org_id: 1 # id of the organization to tie this datasource to
    url: 'http://prometheus.prixfixe.dev' # url of the prom instance
