
[auth]
  cookie_lifetime = "24h0m0s"
  cookie_secret = "HEREISA32CHARSECRETWHICHISMADEUP"
  debug = false
  enable_user_signup = true

[database]
  connection_details = "postgres://dbuser:hunter2@database:5432/prixfixe?sslmode=disable"
  debug = false
  provider = "postgres"

[frontend]
  cache_static_files = false
  debug = true
  static_files_directory = "/frontend"

[meta]
  run_mode = "testing"
  startup_deadline = "1m0s"

[metrics]
  database_metrics_collection_interval = "2s"
  runtime_metrics_collection_interval = "2s"

[server]
  debug = true
  http_port = 8888
