
[auth]
  cookie_domain = "localhost"
  cookie_lifetime = "24h0m0s"
  cookie_secret = "HEREISA32CHARSECRETWHICHISMADEUP"
  debug = true
  enable_user_signup = true
  secure_cookies_only = false

[database]
  connection_details = "postgres://dbuser:hunter2@database:5432/prixfixe?sslmode=disable"
  debug = true
  provider = "postgres"

[frontend]
  cache_static_files = false
  debug = true
  static_files_directory = "/frontend"

[meta]
  debug = true
  run_mode = "development"
  startup_deadline = "1m0s"

[metrics]
  database_metrics_collection_interval = "1s"
  metrics_provider = "prometheus"
  runtime_metrics_collection_interval = "1s"
  tracing_provider = "jaeger"

[server]
  debug = true
  http_port = 8888
