version: "3.8"
services:
    workers:
        container_name: workers
        volumes:
            - source: '../../environments/testing/config_files/integration-tests-postgres.config'
              target: '/etc/service.config'
              type: 'bind'
            - source: '../../'
              target: '/go/src/gitlab.com/prixfixe/prixfixe/cmd/workers'
              type: 'bind'
        build:
            context: '../../'
            dockerfile: 'environments/local/workers.Dockerfile'
    prixfixe-server:
        container_name: api_server
        environment:
            PRIXFIXE_SERVER_LOCAL_CONFIG_STORE_KEY: 'SUFNQVdBUkVUSEFUVEhJU1NFQ1JFVElTVU5TRUNVUkU='
            CONFIGURATION_FILEPATH: '/etc/service.config'
            JAEGER_DISABLED: 'false'
        ports:
            - '8888:8888'
        volumes:
            - source: '../../environments/local/service.config'
              target: '/etc/service.config'
              type: 'bind'
            - source: '../../'
              target: '/go/src/gitlab.com/prixfixe/prixfixe'
              type: 'bind'
        build:
            context: '../../'
            dockerfile: 'environments/local/Dockerfile'
