version: "3.3"
services:
    database:
        image: postgres:latest
        environment:
            POSTGRES_DB: 'prixfixe'
            POSTGRES_PASSWORD: 'hunter2'
            POSTGRES_USER: 'dbuser'
        logging:
            driver: none
        ports:
            - 2345:5432
    grafana:
        image: grafana/grafana
        logging:
            driver: none
        ports:
            - 3000:3000
        links:
            - prometheus
        volumes:
            - source: '../../environments/local/grafana/grafana.ini'
              target: '/etc/grafana/grafana.ini'
              type: 'bind'
            - source: '../../environments/local/grafana/datasources.yaml'
              target: '/etc/grafana/provisioning/datasources/datasources.yml'
              type: 'bind'
            - source: '../../environments/local/grafana/dashboards.yaml'
              target: '/etc/grafana/provisioning/dashboards/dashboards.yml'
              type: 'bind'
            - source: '../../environments/local/grafana/dashboards'
              target: '/etc/grafana/provisioning/dashboards/dashboards'
              type: 'bind'
    prometheus:
        image: quay.io/prometheus/prometheus:v2.0.0
        logging:
            driver: none
        ports:
            - 9090:9090
        volumes:
            - source: "../../environments/local/prometheus/config.yaml"
              target: "/etc/prometheus/config.yaml"
              type: 'bind'
        command: '--config.file=/etc/prometheus/config.yaml --storage.tsdb.path=/prometheus'
    prixfixe-server:
        environment:
            CONFIGURATION_FILEPATH: '/etc/config.toml'
            JAEGER_AGENT_HOST: 'tracing-server'
            JAEGER_AGENT_PORT: '6831'
            JAEGER_SAMPLER_MANAGER_HOST_PORT: 'tracing-server:5778'
            JAEGER_SERVICE_NAME: 'prixfixe-server'
        ports:
            - 80:8888
        links:
            - tracing-server
            - database
        volumes:
            - source: '../../frontend/v1/public'
              target: '/frontend'
              type: 'bind'
            - source: '../../environments/local/config.toml'
              target: '/etc/config.toml'
              type: 'bind'
        build:
            context: '../../'
            dockerfile: 'environments/local/Dockerfile'
        depends_on:
            - prometheus
            - grafana
    tracing-server:
        image: jaegertracing/all-in-one:latest
        logging:
            driver: none
        ports:
            - 6831:6831/udp
            - 5778:5778
            - 16686:16686
