
[auth]
  cookie_domain = ""
  cookie_lifetime = "24h0m0s"
  cookie_secret = "HEREISA32CHARSECRETWHICHISMADEUP"
  debug = false
  enable_user_signup = true
  secure_cookies_only = false

[database]
  connection_details = "postgres://dbuser:hunter2@database:5432/prixfixe?sslmode=disable"
  create_dummy_user = false
  debug = false
  provider = "postgres"

[frontend]
  cache_static_files = false
  debug = false
  static_files_directory = "/frontend"

[meta]
  debug = false
  run_mode = "production"
  startup_deadline = "1m0s"

[metrics]
  database_metrics_collection_interval = "1s"
  metrics_provider = "prometheus"
  runtime_metrics_collection_interval = "1s"
  tracing_provider = "jaeger"

[server]
  debug = false
  http_port = 8888
