global:
  # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  scrape_interval:     15s
  # Evaluate rules every 15 seconds. The default is every 1 minute.
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'prixfixe-server'

    static_configs:
      - targets: ['prixfixe-server:8888']

    # How frequently to scrape targets from this job.
    scrape_interval: 15s

    # Per-scrape timeout when scraping this job.
    scrape_timeout: 15s

    # The HTTP resource path on which to fetch metrics from targets.
    metrics_path: '/metrics'

    # Configures the protocol scheme used for requests.
    scheme: 'http'

    # Optional HTTP URL parameters.
    # params:
    #   key: 'value'

    # Sets the `Authorization` header on every scrape request with the
    # configured username and password.
    # password and password_file are mutually exclusive.
    #  basic_auth:
    #    username: <string>
    #    password: <secret>
    #    password_file: <string>

    # Sets the `Authorization` header on every scrape request with
    # the configured bearer token. It is mutually exclusive with `bearer_token_file`.
    # bearer_token: <secret>

    # Sets the `Authorization` header on every scrape request with the bearer token
    # read from the configured file. It is mutually exclusive with `bearer_token`.
    #  bearer_token_file: /path/to/bearer/token/file

    # Configures the scrape request's TLS settings.
    tls_config:
      # CA certificate to validate API server certificate with.
      #   ca_file: '/path/to/file'

      # Certificate and key files for client cert authentication to the server.
      #   cert_file: '/path/to/file'
      #   key_file: '/path/to/file'

      # ServerName extension to indicate the name of the server.
      # https://tools.ietf.org/html/rfc4366#section-3.1
      #   server_name: ''

      # Disable validation of the server certificate.
      insecure_skip_verify: true

    # Optional proxy URL.
    #  proxy_url: ''

    # Per-scrape limit on number of scraped samples that will be accepted.
    # If more than this number of samples are present after metric relabelling
    # the entire scrape will be treated as failed. 0 means no limit.
    sample_limit:  0


#alerting:
#  alertmanagers:
#    - scheme: https
#      static_configs:
#        - targets:
#            - "1.2.3.4:9093"
#            - "1.2.3.5:9093"
#            - "1.2.3.6:9093"
